# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 458646b3f96da0a75918d5d88944aa726ec636c59467b68f9a8a737366b460810696b4953c8e6e577e2c7866463174b7b6913a41d8b0d33a556b2e33c1f28d51

test:
  secret_key_base: ddb08c25d7b6290bbab39b1ea95783e01b8aa31087e78340138ba87fa12db25f04819ff1cf3b0ab710a2def9684c7e8caebaef3aa4f2eec6233e2e35f0276d94

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
